---
- name: Install docker, docker compose
  hosts: ec2_server
  become: true
  tasks:  

    - name: Install docker and docker compose
      yum: 
        name: docker
        update_cache: true
        state: present

    - name: Install docker compose plugin
      get_url:
        url: "https://github.com/docker/compose/releases/download/v2.34.0/docker-compose-linux-{{ ansible_architecture }}"
        dest: /usr/libexec/docker/cli-plugins/docker-compose
        mode: "+x"

    # to perform sudo systemctl docker start
    - name: Start docker daemon
      systemd:
        name: docker 
        state: started
        enabled: true

# to execute docker command without sudo
# sudo usermod -aG docker ec2-user
- name: Add ec2 user to docker group
  hosts: ec2_server
  become: true
  tasks:
    - name: Add ec2 user to docker group
      user: 
        name: ec2-user
        groups: docker
        append: true

    # reconnect machine, so user and their groups reflect
    - name: Reconnect to server session
      meta: reset_connection

- name: Start docker containers
  hosts: ec2_server
  vars_files:
    - project-vars
  tasks:
    - name: Copy docker compose file
      copy:
        src: /home/mitesh/Documents/GitHub/ansible/docker-compose.yaml
        dest: /home/ec2-user/docker-compose.yaml

    - name: Docker login
      community.docker.docker_login:
        username: miteshch
        password: "{{docker_password}}"

    - name: Start container from docker compose
      community.docker.docker_compose_v2:
        project_src: /home/ec2-user
        state: present