---
- name: Configure nginx web server
  hosts: linodes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    # - name: install nginx server
    #   # apt module
    #   apt: 
    #     name: nginx
    #     state: latest

    # - name: start nginx server
    #   service:
    #     name: nginx
    #     state: started

    - name: uninstall nginx server
      # apt module
      apt: 
        name: nginx
        state: absent

    - name: stop nginx server
      service:
        name: nginx
        state: stopped