- name: Copy docker compose file
  copy:
    src: docker-compose.yaml  # no need to provide path, as file is inside "files" folder
    dest: /home/ec2-user/docker-compose.yaml

- name: Docker login
  community.docker.docker_login:
    username: "{{ docker_username }}"
    password: "{{ docker_password }}"

- name: Start container from docker compose
  community.docker.docker_compose_v2:
    project_src: /home/ec2-user
    state: present